---
services:
  kali:
    build:
      context: .
      dockerfile: build/kali.Dockerfile
    ports:
      - "127.0.0.1:6901:6901"
    environment:
      VNC_PW: "password"
    cap_add:
      - NET_ADMIN
      - NET_RAW

  defender:
    build:
      context: .
      dockerfile: build/defender.Dockerfile
    profiles: [threat-detection, authentication, blue-team, privacy]
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  iot:
    build:
      context: .
      dockerfile: build/iot.Dockerfile
    profiles: [iot]

  cowrie:
    image: cowrie/cowrie
    profiles: [threat-detection]

  # Used for the "11 - Red team" lab
  juice-shop:
    image: bkimminich/juice-shop
    profiles: [red-team]
    ports:
      - "127.0.0.1:3000:3000"
